# Generated by Django 5.1.6 on 2025-02-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_whatsappmessage_scheduled_at_whatsappstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
