# Generated by Django 5.1.6 on 2025-02-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_alter_whatsappmessage_status_contact_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='user',
        ),
    ]
